In [ ]:
'''l = [3,4,5,6,7 , [23,456,67,8,78,78] , [345,56,87,8,98,9] , (234,6657,6) , {"key1" :"sudh" , 234:[23,45,656]}]
1 . Try to reverse a list
2.  try to access 234 out of this list
3 . try to access 456
4 . Try to extract only a list collection form list l
5 . Try to extract "sudh"
6 . Try to list all the key in dict element avaible in list
7 . Try to extract all the value element form dict available in list'''

In [1]:
# 1 . Try to reverse a list
l = [3,4,5,6,7 , [23,456,67,8,78,78] , [345,56,87,8,98,9] , (234,6657,6) , {"key1" :"sudh" , 234:[23,45,656]}]
l[::-1]

[{'key1': 'sudh', 234: [23, 45, 656]},
 (234, 6657, 6),
 [345, 56, 87, 8, 98, 9],
 [23, 456, 67, 8, 78, 78],
 7,
 6,
 5,
 4,
 3]

In [14]:
# 2.  try to access 234 out of this list

# Define the list
l = [3, 4, 5, 6, 7,
     [23, 456, 67, 8, 78, 78],
     [345, 56, 87, 8, 98, 9],
     (234, 6657, 6),
     {"key1": "sudh", 234: [23, 45, 656]}
]

# Accessing 234 from the tuple
tuple_value = l[7][0]
print("234 from the tuple:", tuple_value)

# Checking if 234 is a key in the dictionary
dictionary = l[8]
if 234 in dictionary:
    print("234 is a key in the dictionary:", 234)
else:
    print("234 is not a key in the dictionary")

234 from the tuple: 234
234 is a key in the dictionary: 234

In [15]:
# 3 . try to access 456

# Define the list:
l = [
    3, 4, 5, 6, 7,
    [23, 456, 67, 8, 78, 78],
    [345, 56, 87, 8, 98, 9],
    (234, 6657, 6),
    {"key1": "sudh", 234: [23, 45, 656]}
]

# Accessing 456 from the list
list_value = l[5][1]
print("456 from the list:", list_value)

456 from the list: 456

In [16]:
# 4 . Try to extract only a list collection form list l

# Define the list
l = [3, 4, 5, 6, 7,
     [23, 456, 67, 8, 78, 78],
     [345, 56, 87, 8, 98, 9],
     (234, 6657, 6),
     {"key1": "sudh", 234: [23, 45, 656]}
]

# Extracting the list collection
list_collection = l[5:7]
print("List collection:", list_collection)

List collection: [[23, 456, 67, 8, 78, 78], [345, 56, 87, 8, 98, 9]]

In [17]:
# 5 . Try to extract "sudh"

 # Define the list
l = [3, 4, 5, 6, 7,
     [23, 456, 67, 8, 78, 78],
     [345, 56, 87, 8, 98, 9],
     (234, 6657, 6),
     {"key1": "sudh", 234: [23, 45, 656]}
]

# Extracting "sudh" from the dictionary
dictionary = l[8]
sudh_value = dictionary["key1"]
print("sudh from the dictionary:", sudh_value)

sudh from the dictionary: sudh

In [18]:
# 6 . Try to list all the key in dict element avaible in list

# Define the list
l = [3, 4, 5, 6, 7,
     [23, 456, 67, 8, 78, 78],
     [345, 56, 87, 8, 98, 9],
     (234, 6657, 6),
     {"key1": "sudh", 234: [23, 45, 656]}
]

# Extracting all the keys from the dictionary
dictionary = l[8]
all_keys = dictionary.keys()
print("All keys in the dictionary:", all_keys)

All keys in the dictionary: dict_keys(['key1', 234])

In [19]:
# 7 . Try to extract all the value element form dict available in list

# Define the list
l = [3, 4, 5, 6, 7,
     [23, 456, 67, 8, 78, 78],
     [345, 56, 87, 8, 98, 9],
     (234, 6657, 6),
     {"key1": "sudh", 234: [23, 45, 656]}
]

# Extracting all the values from the dictionary
dictionary = l[8]
all_values = dictionary.values()
print("All values in the dictionary:", all_values)

All values in the dictionary: dict_values(['sudh', [23, 45, 656]])