Mini-Project 1:
Load a small dataset (like a list of 10 items) with columns like "Name", "Age", "Country".
Extract the data for people from a specific country.

In [5]:
import pandas as pd

# Step 1: Create a small dataset
data = {
    "Name": ["John", "Emma", "Mia", "Lucas", "Sophia", "Liam", "Olivia", "Noah", "Ava", "Ethan"],
    "Age": [28, 22, 19, 34, 26, 30, 21, 25, 23, 29],
    "Country": ["USA", "UK", "France", "USA", "Canada", "UK", "USA", "Canada", "France", "USA"]
}

# Step 2: Load data into a DataFrame
df = pd.DataFrame(data)

# Display the dataset
print(df)

# Step 3: Extract data for a specific country (e.g. , USA)
specific_country = 'USA'
filtered_data = df[df['Country'] == specific_country]

# Display the filtered data
print(f"\nData for people from {specific_country}")
print(filtered_data)

     Name  Age Country
0    John   28     USA
1    Emma   22      UK
2     Mia   19  France
3   Lucas   34     USA
4  Sophia   26  Canada
5    Liam   30      UK
6  Olivia   21     USA
7    Noah   25  Canada
8     Ava   23  France
9   Ethan   29     USA

Data for people from USA
     Name  Age Country
0    John   28     USA
3   Lucas   34     USA
6  Olivia   21     USA
9   Ethan   29     USA